### PR TITLE
Avoid exceptions in Minion._result

### LINKED ISSUE #15: Bug: Minion._result can cause process killing exception
`Minion._result` calls `PgBackend.listJobs` which may fail with an exception, but since `_result` might be called from a `setTimeout`, this exception may eventually kill the process.

The obvious solution would be to try-catch any exception in `_result` and then call the `reject` function passed into the method.

WDYT?

### PR DESCRIPTION
**Pull request by DrMurx**
Fixes #15

### CODE REVIEW

File: src/minion.ts [hunk 1]
```diff
@@ -299,17 +299,22 @@ export default class Minion {
...
+        resolve(info);
+      } else if (info.state === 'failed') {
+        reject(info);
+      } else if (signal !== null && signal.aborted === true) {
+        reject(new AbortError());
+      } else {
+        setTimeout(rerun, interval);
+      }
+    } catch (error: any) {
+      setTimeout(rerun, interval);
```
Comment (kraih) [inline src/minion.ts:317]: Wouldn't a single `finally` block solve this with less code? 🤔

Comment (DrMurx) [reply src/minion.ts:317]: A single `finally` block would be executed every time after we've enter the `try` block, even if we called `resolve` or `reject` (in those cases, we don't need another invocation of `_result`).

Comment (DrMurx) [reply src/minion.ts:317]: If you don't like the length `try` block, it could also be implemented like this, at the expense of using `let` instead of `const`:

```ts
let info: JobInfo;
try {
  info = (await this.backend.listJobs(0, 1, {ids: [id]})).jobs[0];
} catch (error: any) {
  setTimeout(rerun, interval);
  return;
}

if (info === undefined) {
...
```

There would be a few alternative code flows to avoid duplicating the `setTimeout` command, but I'd consider each of them less readable.
